import bourhine2 from './assets/img/bourhine2.jpeg'
import walid1    from './assets/img/walid1.jpeg'
export const ARTWORKS = [
  // ── Abdallah Bourhine (3 works) ──────────────────────────────────────────
  {
    id:          'bilmawn',
    title:       'Bilmawn',
    student:     'Abdallah Bourhine',
    initials:    'AB',
    medium:      'Digitale',
    year:        2024,
    category:    'Illustration',
    description: "Une illustration vibrante d'un personnage à la peau bleue portant une coiffe à cornes, encadré par des instruments traditionnels.",
    imageUrl:    '/art1.jpeg', // 👈 تأكد واش .jpg ولا .png
  },
  {
    id:          'free-palestine',
    title:       'Free Palestine',
    student:     'Abdallah Bourhine',
    initials:    'AB',
    medium:      'Digitale',
    year:        2023,
    category:    'Illustration',
    description: "Un personnage solennel vêtu de vert et coiffé d'un keffieh, tenant délicatement une fleur orange sur fond noir.",
    imageUrl:    bourhine2, 
  },
  {
    id:          'bourhine-3',
    title:       'Œuvre III',
    student:     'Abdallah Bourhine',
    initials:    'AB',
    medium:      'Digitale',
    year:        2024,
    category:    'Illustration',
    description: "Troisième création digitale d'Abdallah Bourhine, explorant forme et couleur.",
    imageUrl:    '/img/bourhine3.jpeg',
  },

  // ── Zeyati Walid (3 works) ───────────────────────────────────────────────
  {
    id:          'le-zouphri',
    title:       'Le Zouphri',
    student:     'Zyati Walid',
    initials:    'ZW',
    medium:      'Digitale',
    year:        2024,
    category:    'Portrait',
    description: "Un jeune homme aux cheveux bruns bouclés, vêtu d'un gilet marron, avec une expression candide.",
    imageUrl:    walid1,
  },
  {
    id:          'iben-batota',
    title:       'Iben Batota',
    student:     'Zyati Walid',
    initials:    'ZW',
    medium:      'Digitale',
    year:        2024,
    category:    'Portrait',
    description: "Un voyageur barbu coiffé d'un turban vert, portant un parchemin dans le dos et tenant un livre rouge.",
    imageUrl:    '/img/walid2.jpeg',
  },
  {
    id:          'lgazar',
    title:       'LGAZAR',
    student:     'Zyati Walid',
    initials:    'ZW',
    medium:      'Digitale',
    year:        2024,
    category:    'Character Design',
    description: "Planche de conception d'un personnage cartoonesque bedonnant au gros nez rose et à la casquette rouge.",
    imageUrl:    '/img/walid3.jpeg',
  },

  // ── Nabil Mimouni (3 works) ──────────────────────────────────────────────
  {
    id:          'ellie-tlou',
    title:       'Ellie (TLOU)',
    student:     'Nabil Mimouni',
    initials:    'NM',
    medium:      'Papier',
    year:        2024,
    category:    'Dessin Traditionnel',
    description: "Portrait réaliste au crayon d'Ellie, personnage principal du jeu The Last of Us.",
    imageUrl:    '/img/nabil1.jpeg',
  },
  {
    id:          'nabil-2',
    title:       'Dessin II',
    student:     'Nabil Mimouni',
    initials:    'NM',
    medium:      'Papier',
    year:        2024,
    category:    'Dessin Traditionnel',
    description: "Deuxième œuvre sur papier de Nabil Mimouni, maîtrise du trait et des ombres.",
    imageUrl:    '/img/nabil2.jpeg',
  },
  {
    id:          'tuk-ilu',
    title:       'Tuk & Ilu (Avatar)',
    student:     'Nabil Mimouni',
    initials:    'NM',
    medium:      'Papier',
    year:        2025,
    category:    'Dessin Traditionnel',
    description: "Un dessin à l'encre représentant un personnage aux cheveux tentaculaires parmi des poissons volants.",
    imageUrl:    '/img/nabil3.jpeg',
  },

  // ── Yebda Nada (3 works) ─────────────────────────────────────────────────
  {
    id:          'metamorphose',
    title:       'Métamorphose du Regard',
    student:     'Yebda Nada',
    initials:    'YN',
    medium:      'Papier',
    year:        2024,
    category:    'Illustration',
    description: "Illustration expressive où le regard se transforme, mêlant réalisme et abstraction.",
    imageUrl:    '/img/nada1.jpeg',
  },
  {
    id:          'nada-2',
    title:       'Illustration II',
    student:     'Yebda Nada',
    initials:    'YN',
    medium:      'Papier',
    year:        2024,
    category:    'Illustration',
    description: "Deuxième illustration de Nada, jouant sur les contrastes et la composition.",
    imageUrl:    '/img/nada2.jpeg',
  },
  {
    id:          'nada-3',
    title:       'Illustration III',
    student:     'Yebda Nada',
    initials:    'YN',
    medium:      'Papier',
    year:        2024,
    category:    'Illustration',
    description: "Troisième œuvre de Nada, exploration des formes organiques et de la ligne.",
    imageUrl:    '/img/nada3.jpeg',
  },
];